# Generated by Django 5.2.1 on 2025-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_id_usersprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
