# Generated by Django 5.2.3 on 2025-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='Name of the plan at the time of purchase', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(help_text='Payment status (e.g., Succeeded, Failed, Pending)', max_length=50)),
                ('plan_type', models.CharField(help_text='Type of plan purchased (e.g., Basic, Premium)', max_length=100)),
                ('start_date', models.DateTimeField(help_text='Subscription start date related to this payment')),
                ('end_date', models.DateTimeField(help_text='Subscription end date related to this payment')),
                ('purchases_date', models.DateTimeField(help_text='Date and time of the purchase')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-purchases_date'],
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=100)),
                ('purchases_date', models.DateField()),
                ('transaction_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(help_text='Type of subscription plan (e.g., Basic, Premium)', max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(help_text='Subscription status (e.g., Active, Inactive, Cancelled)', max_length=50)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
    ]
