# Generated by Django 5.2.1 on 2025-05-25 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(help_text='Type of subscription plan (e.g., Basic, Premium)', max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(help_text='Subscription status (e.g., Active, Inactive, Cancelled)', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='Name of the plan at the time of purchase', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(help_text='Payment status (e.g., Succeeded, Failed, Pending)', max_length=50)),
                ('plan_type', models.CharField(help_text='Type of plan purchased (e.g., Basic, Premium)', max_length=100)),
                ('start_date', models.DateTimeField(help_text='Subscription start date related to this payment')),
                ('end_date', models.DateTimeField(help_text='Subscription end date related to this payment')),
                ('purchases_date', models.DateTimeField(help_text='Date and time of the purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.subscriptions')),
            ],
        ),
    ]
