# Generated by Django 5.2.1 on 2025-05-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-purchases_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
