# Generated by Django 5.2.3 on 2025-07-17 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0003_remove_purchases_user_remove_subscriptions_user_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plan', models.CharField(choices=[('MONTHLY', 'Monthly Subscription'), ('LIFETIME', 'Lifetime Access (One-Time)')], help_text='The plan the user is currently on.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled'), ('PAST_DUE', 'Past Due')], default='INACTIVE', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, help_text='Date when the subscription first started or the current period began.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='For MONTHLY plan, this is the end of the current billing cycle. For LIFETIME, this is null.', null=True)),
                ('gateway', models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'Paypal'), ('MANUAL', 'Manual/Admin')], max_length=20, null=True)),
                ('gateway_subscription_id', models.CharField(blank=True, help_text='e.g., Stripe Subscription ID (sub_...). Only for MONTHLY plan.', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
