# Generated by Django 5.2.3 on 2025-06-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Is Template Meal?'),
        ),
    ]
